#!/bin/sh
set -eu
. /usr/libexec/haproxy-manager/common.sh

BASE="$(backup_dir)"
STAMP="$(date +%Y%m%d-%H%M%S)"

mkdir -p "$BASE"
BASE="$(cd "$BASE" && pwd -P)"
DIR="$BASE/$STAMP"
mkdir -p "$DIR"
[ -f /etc/config/firewall ] && cp /etc/config/firewall "$DIR/firewall"
[ -f /etc/config/uhttpd ] && cp /etc/config/uhttpd "$DIR/uhttpd"
[ -f /etc/config/haproxy_manager ] && cp /etc/config/haproxy_manager "$DIR/haproxy_manager"
[ -f "$HAPROXY_CFG" ] && cp "$HAPROXY_CFG" "$DIR/haproxy.cfg"

printf '%s\n' "$DIR" > "$BASE/LAST"

count=0
for old in $(find "$BASE" -maxdepth 1 -type d -name '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9]' 2>/dev/null | sort -r); do
	count=$((count + 1))
	[ "$count" -le "$BACKUP_LIMIT" ] && continue
	case "$old" in
		"$BASE"/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9])
			rm -f "$old"/*
			rmdir "$old"
		;;
	esac
done

printf '%s\n' "$DIR"
